name: fmt
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Cargo Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Rust Binaries
        run: |
          cargo binstall -y --force leptosfmt
          cargo binstall -y --force trunk

      - name: Release
        run: make release

      - name: Run
        run: cargo fmt --all -- --check
