name: upload_artifacts

on:
  release:
    types:
      - published

jobs:
  build:
    name: Setup workflows for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        name:
          - linux
          - macos

      include:
        - name: linux
          os: ubuntu-latest
          artifact_name: http-server
          asset_name: http-server

        - name: macos
          os: macos-linux
          artifact_name: http-server
          asset_name: http-server

    steps:
      - name: Checkout project files
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Cargo Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Rust Binaries
        run: |
          cargo binstall -y --force leptosfmt
          cargo binstall -y --force trunk

      - name: Release
        run: make release

      - name: Upload release artifacts
        uses: actions/github-script@v5
        env:
          ARTIFACT_NAME: ${{ matrix.artifact_name }}
          ASSET_NAME: ${{ matrix.asset_name }}
        with:
          script: |
            const script = require('./.github/workflows/scripts/upload-artifacts.js');
            console.log(script({ github, context }));
